xcodeproj 'CustomFormatters'
workspace '../../Lumberjack'

def import_pods
  pod 'CocoaLumberjack', :path => '../../'
end

target :CFo_osx do
  platform :osx, '10.7'
  link_with 'CustomFormatters'
  import_pods
end

