version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      day: tuesday

  - package-ecosystem: swift
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      day: tuesday
