#!/bin/bash

# Get full user name of current user
# E.g. "Robbie Hanson"
full=$(osascript -e "tell application \"System Events\"" -e "get the full name of the current user" -e "end tell")
#echo $full

# Convert to lower case
# E.g. "robbie hanson"
full_lower=$(echo $full | awk '{print tolower($0)}')
#echo $full_lower

# Replace spaces with underscores
# E.g. "robbie_hanson"
full_lower_underscore=$(echo ${full_lower// /_})
#echo $full_lower_underscore

echo "// This file is automatically generated" > ${SRCROOT}/PerUserLogLevels/LumberjackUser.h
echo "#define $full_lower_underscore 1" >> ${SRCROOT}/PerUserLogLevels/LumberjackUser.h
