source 'https://github.com/CocoaPods/Specs'

xcodeproj 'CocoaLumberjack Tests'
workspace '../Framework/Lumberjack'
inhibit_all_warnings!

def import_pods
  pod 'Expecta'
  pod 'OCMock'
  pod 'CocoaLumberjack', :path => '../'
end

target :ios do
  platform :ios, '5.1.1'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.7'
  link_with 'OS X Tests'
  import_pods
end
