source 'https://github.com/CocoaPods/Specs'

use_frameworks!

project 'CocoaLumberjack Tests'
workspace '../Framework/Lumberjack'
inhibit_all_warnings!

def import_pods
  pod 'Expecta'
  pod 'OCMock'
  pod 'CocoaLumberjack', :path => '../'
end

target :'iOS Tests' do
  platform :ios, '8.0'
  import_pods
end

target :'OS X Tests' do
  platform :osx, '10.10'
  import_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configuration_list.build_configurations.each do |build_configuration|
            build_configuration.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
