xcodeproj 'CoreDataLogger'
workspace '../../Lumberjack'

def import_pods
  pod 'CocoaLumberjack', :path => '../../'
end

target :CDL_osx do
  platform :osx, '10.7'
  link_with 'CoreDataLogger'
  import_pods
end

