xcodeproj 'TestXcodeColors'
workspace '../../../Testing'

def import_pods
  pod 'CocoaLumberjack', :path => '../../../'
end

target :TXC_osx do
  platform :osx, '10.7'
  link_with 'TestXcodeColors'
  import_pods
end

