source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'OverflowTestMac'
workspace '../Demos'

def import_pods
  pod 'CocoaLumberjack', :path => '../../'
end

target :OTM_osx do
  platform :osx, '10.7'
  link_with 'OverflowTestMac'
  import_pods
end

