source 'https://github.com/CocoaPods/Specs.git'

project '../Lumberjack'
workspace 'Lumberjack'

target 'iOSLibStaticTest' do
  platform :ios, '8.0'
  pod 'CocoaLumberjack', :path => '../'
end

target 'FmwkTest' do
  platform :osx, '10.10'
  use_frameworks!
  pod 'CocoaLumberjack/CLI', :path => '../'
end

target 'iOSSwiftTest' do
  platform :ios, '8.0'
  use_frameworks!
  pod 'CocoaLumberjack/Swift', :path => '../'
  pod 'CocoaLumberjack/Extensions', :path => '../'
end

target 'SwiftTest' do
  platform :osx, '10.10'
  use_frameworks!
  pod 'CocoaLumberjack/Swift', :path => '../'
  pod 'CocoaLumberjack/CLI', :path => '../'
end

target 'tvOSSwiftTest' do
  platform :tvos, '9.0'
  use_frameworks!
  pod 'CocoaLumberjack/Swift', :path => '../'
  pod 'CocoaLumberjack/Extensions', :path => '../'
end

target 'watchOSSwiftTest Extension' do
  platform :watchos, '2.0'
  use_frameworks!
  pod 'CocoaLumberjack/Swift', :path => '../'
  pod 'CocoaLumberjack/Extensions', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configuration_list.build_configurations.each do |build_configuration|
            build_configuration.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
