source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'DispatchQueueLogger'
workspace '../Demos'

def import_pods
  pod 'CocoaLumberjack', :path => '../../'
end

target :DQL_osx do
  platform :osx, '10.7'
  link_with 'DispatchQueueLogger'
  import_pods
end

