xcodeproj 'CLI'
workspace '../../Lumberjack'
inhibit_all_warnings!

def import_pods
  pod 'CocoaLumberjack/CLI', :path => '../../'
end

target :osx do
  platform :osx, '10.7'
  link_with 'CLI'
  import_pods
end

