source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'RegisteredLoggingTest'
workspace '../../Demos'

def import_pods
  pod 'CocoaLumberjack', :path => '../../../'
end

target :RLT_osx do
  platform :osx, '10.7'
  link_with 'RegisteredLoggingTest'
  import_pods
end

