xcodeproj 'CustomLogLevels'
workspace '../../Lumberjack'
inhibit_all_warnings!

def import_pods
  pod 'CocoaLumberjack', :path => '../../'
end

target :osx do
  platform :osx, '10.7'
  link_with 'CustomLogLevels'
  import_pods
end

