source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'RegisteredLoggingTest'
workspace '../../Demos'

def import_pods
  pod 'CocoaLumberjack', :path => '../../../'
end

target :RLT_ios do
  platform :ios, '5.0'
  link_with 'RegisteredLoggingTest'
  import_pods
end

